// Code generated by oapigen, DO NOT EDIT.

package client

type ListItemsRequestAuditData struct {
	Limit *int
	Tag   *string
}

func (req *ListItemsRequest) GetAuditData() any {
	am := ListItemsRequestAuditData{
		Limit: req.Limit,
		Tag:   req.Tag,
	}
	return am
}

type CreateItemRequestAuditData struct {
	Body any
}

func (req *CreateItemRequest) GetAuditData() any {
	am := CreateItemRequestAuditData{}
	am.Body = req.Body.GetAuditData()
	return am
}

type GetItemRequestAuditData struct {
	ID string
}

func (req *GetItemRequest) GetAuditData() any {
	am := GetItemRequestAuditData{
		ID: req.ID,
	}
	return am
}

type UpdateItemRequestAuditData struct {
	Body any
}

func (req *UpdateItemRequest) GetAuditData() any {
	am := UpdateItemRequestAuditData{}
	am.Body = req.Body.GetAuditData()
	return am
}

type DeleteItemRequestAuditData struct {
	ID string
}

func (req *DeleteItemRequest) GetAuditData() any {
	am := DeleteItemRequestAuditData{
		ID: req.ID,
	}
	return am
}

type ListItemsResponse200AuditData struct {
	Payload any
}

func (resp *ListItemsResponse) Response200AuditData() ListItemsResponse200AuditData {
	am := ListItemsResponse200AuditData{}
	if resp.Response200 != nil {
		am.Payload = resp.Response200.GetAuditData()
	}
	return am
}

type CreateItemResponse201AuditData struct {
	Payload any
}

func (resp *CreateItemResponse) Response201AuditData() CreateItemResponse201AuditData {
	am := CreateItemResponse201AuditData{}
	if resp.Response201 != nil {
		am.Payload = resp.Response201.GetAuditData()
	}
	return am
}

type GetItemResponse200AuditData struct {
	Payload any
}

func (resp *GetItemResponse) Response200AuditData() GetItemResponse200AuditData {
	am := GetItemResponse200AuditData{}
	if resp.Response200 != nil {
		am.Payload = resp.Response200.GetAuditData()
	}
	return am
}

type UpdateItemResponse200AuditData struct {
	Payload any
}

func (resp *UpdateItemResponse) Response200AuditData() UpdateItemResponse200AuditData {
	am := UpdateItemResponse200AuditData{}
	if resp.Response200 != nil {
		am.Payload = resp.Response200.GetAuditData()
	}
	return am
}
