package gogen

import (
	"go/parser"
	"go/token"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestNewFileFactory_ToolName(t *testing.T) {
	ff := NewFileFactory("oapigen")
	assert.Equal(t, "oapigen", ff.toolName)
}

func TestCreate_HeaderAndPackage(t *testing.T) {
	ff := NewFileFactory("oapigen")
	f := ff.Create(&File{Package: "model", Body: []byte("")})
	got := string(f.Content())

	want := "// Code generated by oapigen, DO NOT EDIT.\n\npackage model\n"
	assert.Equal(t, want, got)
}

func TestCreate_WithBody(t *testing.T) {
	ff := NewFileFactory("oapigen")
	f := ff.Create(&File{Package: "main", Body: []byte("var x = 1\n")})
	got := string(f.Content())

	assert.Contains(t, got, "var x = 1", "expected body; got:\n%s", got)
	assert.Contains(t, got, "package main", "expected package decl; got:\n%s", got)
}

func TestCreate_ImportsSorted(t *testing.T) {
	ff := NewFileFactory("oapigen")
	f := ff.Create(&File{
		Package: "model",
		Imports: []Import{
			{Path: "fmt"},
			{Path: "os"},
			{Path: "bytes"},
		},
		Body: []byte("var _ = fmt.Sprintf\nvar _ = os.Args\nvar _ = bytes.NewBuffer\n"),
	})
	got := string(f.Content())

	assert.Contains(t, got, `"bytes"`)
	assert.Contains(t, got, `"fmt"`)
	assert.Contains(t, got, `"os"`)
	bytesIdx := strings.Index(got, `"bytes"`)
	fmtIdx := strings.Index(got, `"fmt"`)
	osIdx := strings.Index(got, `"os"`)
	assert.True(t, bytesIdx < fmtIdx && fmtIdx < osIdx, "imports not sorted; got bytes=%d, fmt=%d, os=%d", bytesIdx, fmtIdx, osIdx)
}

func TestCreate_ImportWithAlias(t *testing.T) {
	ff := NewFileFactory("oapigen")
	f := ff.Create(&File{
		Package: "model",
		Imports: []Import{{Path: "git.example.com/lib", Alias: "lib"}},
		Body:    []byte("var _ = lib.Use\n"),
	})
	got := string(f.Content())
	assert.Contains(t, got, `lib "git.example.com/lib"`)
}

func TestCreate_ImportAliasTrimmed(t *testing.T) {
	ff := NewFileFactory("oapigen")
	f := ff.Create(&File{
		Package: "model",
		Imports: []Import{{Path: "fmt", Alias: "  f  "}},
		Body:    []byte("var _ = f.Sprintf\n"),
	})
	got := string(f.Content())
	assert.Contains(t, got, `f "fmt"`)
}

func TestCreate_NoImportBlockWhenEmpty(t *testing.T) {
	ff := NewFileFactory("oapigen")
	f := ff.Create(&File{Package: "model", Body: []byte("var x = 1\n")})
	got := string(f.Content())
	assert.NotContains(t, got, "import (")
}

func TestCreate_GofmtApplied(t *testing.T) {
	ff := NewFileFactory("oapigen")
	// Намеренно «плохой» отступ — gofmt должен нормализовать
	body := []byte("func main(){\nif true {\nreturn\n}\n}\n")
	f := ff.Create(&File{Package: "main", Body: body})
	got := string(f.Content())

	assert.Contains(t, got, "\tif true {", "expected gofmt-normalized indentation; got:\n%s", got)
}

func TestCreate_InvalidGoFallback(t *testing.T) {
	ff := NewFileFactory("oapigen")
	body := []byte("this is not valid go code !!!")
	f := ff.Create(&File{Package: "main", Body: body})
	got := string(f.Content())

	assert.Contains(t, got, "this is not valid go code !!!", "expected fallback raw content")
	assert.Contains(t, got, "// Code generated by oapigen, DO NOT EDIT.", "expected header in fallback")
}

func TestCreate_ResultSatisfiesCodegenFile(t *testing.T) {
	ff := NewFileFactory("oapigen")
	f := ff.Create(&File{Package: "main", Body: nil})
	require.NotNil(t, f)
	assert.NotNil(t, f.Content())
}

func TestCreate_ValidGoCompiles(t *testing.T) {
	ff := NewFileFactory("oapigen")
	body := []byte(`
type User struct {
	Name string
	Age  int
}

func NewUser(name string, age int) *User {
	return &User{Name: name, Age: age}
}
`)
	f := ff.Create(&File{
		Package: "model",
		Imports: []Import{},
		Body:    body,
	})
	got := string(f.Content())

	fset := token.NewFileSet()
	_, err := parser.ParseFile(fset, "generated.go", got, parser.AllErrors)
	assert.NoError(t, err, "generated file should parse; content:\n%s", got)
}

func TestImport_PackageAndType(t *testing.T) {
	imp := Import{
		Path:    "nschugorev/oapigenerator/go/common/model",
		Alias:   "common",
		Package: "model",
		Type:    LocalImport,
	}
	assert.Equal(t, "model", imp.Package)
	assert.Equal(t, LocalImport, imp.Type)
}

func TestImportType_ZeroValue(t *testing.T) {
	var imp Import

	assert.Equal(t, ImportType(0), imp.Type)
	assert.Equal(t, LocalImport, imp.Type, "zero ImportType must equal LocalImport")
}
