// Package gogen — рендер структурного описания Go-файла (gogen.File) в
// gofmt-совместимый исходник (codegen.File). Замена
// git.mws-team.ru/mws/devp/platform-go/pkg/codegen/gogen.
//
// В первой итерации поддерживается минимальное управление импортами: список
// Import без группировки std/external/local. Категоризация и дедупликация
// добавятся, когда конкретный генератор (T13+) их реально потребует.
package gogen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"

	"nschugorev/oapigenerator/internal/codegen"
)

// Import описывает одну Go-импорт-спеку: путь и опциональный алиас.
type Import struct {
	Path  string
	Alias string
}

// File — структурное описание Go-файла: пакет, импорты, тело.
// Не реализует codegen.File — для рендера используйте FileFactory.Create.
type File struct {
	Package string
	Imports []Import
	Body    []byte
}

// FileFactory рендерит *File в codegen.File с gofmt-форматированием и
// заголовком «Code generated by <toolName>, DO NOT EDIT.».
type FileFactory struct {
	toolName string
}

// NewFileFactory создаёт FileFactory с заданным именем инструмента-генератора
// (используется в заголовке файла).
func NewFileFactory(toolName string) *FileFactory {
	return &FileFactory{toolName: toolName}
}

// Create рендерит f в codegen.File:
//  1. Заголовок-комментарий
//  2. package <Package>
//  3. import-блок (если есть импорты), отсортированный по Path
//  4. Body
//  5. go/format.Source для gofmt-нормализации
//
// Если format.Source падает (тело синтаксически некорректно), возвращается
// неотформатированный исходник — генерация не должна падать на полпути;
// ошибку увидит компилятор сгенерированного кода.
func (ff *FileFactory) Create(f *File) codegen.File {
	var buf bytes.Buffer
	_, _ = fmt.Fprintf(&buf, "// Code generated by %s, DO NOT EDIT.\n\n", ff.toolName)
	_, _ = fmt.Fprintf(&buf, "package %s\n\n", f.Package)
	if len(f.Imports) > 0 {
		renderImports(&buf, f.Imports)
		buf.WriteByte('\n')
	}
	buf.Write(f.Body)

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return codegen.NewFile(buf.Bytes())
	}
	return codegen.NewFile(formatted)
}

func renderImports(buf *bytes.Buffer, imports []Import) {
	sorted := make([]Import, len(imports))
	copy(sorted, imports)
	sort.SliceStable(sorted, func(i, j int) bool {
		return sorted[i].Path < sorted[j].Path
	})
	buf.WriteString("import (\n")
	for _, imp := range sorted {
		imp.Alias = strings.TrimSpace(imp.Alias)
		if imp.Alias != "" {
			_, _ = fmt.Fprintf(buf, "\t%s %q\n", imp.Alias, imp.Path)
			continue
		}
		_, _ = fmt.Fprintf(buf, "\t%q\n", imp.Path)
	}
	buf.WriteString(")\n")
}
