// Code generated by oapigen, DO NOT EDIT.

package server

import (
	"context"
	client "nschugorev/oapigenerator/testdata/minimal/golden/interfaces/client"
)

type Server interface {
	ListItems(ctx context.Context, req *client.ListItemsRequest) (*client.ListItemsResponse, error)
	CreateItem(ctx context.Context, req *client.CreateItemRequest) (*client.CreateItemResponse, error)
	GetItem(ctx context.Context, req *client.GetItemRequest) (*client.GetItemResponse, error)
	DeleteItem(ctx context.Context, req *client.DeleteItemRequest) (*client.DeleteItemResponse, error)
}
