// Code generated by oapigen (v1.3.0), DO NOT EDIT.

package model

import (
	model "github.com/ilovepitsa/oapicodegen/testdata/onefile/golden/onefile/model"
	common "github.com/ilovepitsa/oapicodegen/testdata/onefile/golden/onefile/model/common"
)

type UserRequestAuditData struct {
	Email   string                 `json:"email" yaml:"email"`
	Name    string                 `json:"name" yaml:"name"`
	Status  *UserStatus            `json:"status,omitempty" yaml:"status,omitempty"`
	Address *common.AddressRequest `json:"address,omitempty" yaml:"address,omitempty"`
}

func (m UserRequest) GetAuditData() any {
	var am UserRequestAuditData
	am.Email = m.Email
	am.Name = m.Name
	am.Status = m.Status
	am.Address = m.Address
	return am
}

type UserResponseAuditData struct {
	ID        *string                 `json:"id,omitempty" yaml:"id,omitempty"`
	Email     string                  `json:"email" yaml:"email"`
	Name      string                  `json:"name" yaml:"name"`
	Status    *UserStatus             `json:"status,omitempty" yaml:"status,omitempty"`
	Address   *common.AddressResponse `json:"address,omitempty" yaml:"address,omitempty"`
	CreatedAt *model.UTCTime          `json:"createdAt,omitempty" yaml:"createdAt,omitempty"`
}

func (m UserResponse) GetAuditData() any {
	var am UserResponseAuditData
	am.ID = m.ID
	am.Email = m.Email
	am.Name = m.Name
	am.Status = m.Status
	am.Address = m.Address
	am.CreatedAt = m.CreatedAt
	return am
}
