// Code generated by oapigen (v1.3.6), DO NOT EDIT.

package model

import (
	common "github.com/ilovepitsa/oapicodegen/testdata/onefile/golden/onefile/model/common"
)

func UserRequestToResponse(req UserRequest) UserResponse {
	var resp UserResponse
	resp.Email = req.Email
	resp.Name = req.Name
	resp.Status = req.Status
	if req.Address != nil {
		v := common.AddressRequestToResponse(*req.Address)
		resp.Address = &v
	}
	return resp
}
