// Code generated by oapigen (v1.3.5), DO NOT EDIT.

package model

type UserStatus string

const (
	UserStatusActive    UserStatus = "active"
	UserStatusSuspended UserStatus = "suspended"
	UserStatusDeleted   UserStatus = "deleted"
)
