// Code generated by oapigen (v1.2.0), DO NOT EDIT.

package model

import (
	model "github.com/ilovepitsa/oapicodegen/testdata/onefile/golden/onefile/model"
	common "github.com/ilovepitsa/oapicodegen/testdata/onefile/golden/onefile/model/common"
)

type UserRequest struct {
	Email   string                 `json:"email" yaml:"email"`
	Name    string                 `json:"name" yaml:"name"`
	Status  *UserStatus            `json:"status,omitempty" yaml:"status,omitempty"`
	Address *common.AddressRequest `json:"address,omitempty" yaml:"address,omitempty"`
}

type UserResponse struct {
	ID        *string                 `json:"id,omitempty" yaml:"id,omitempty"`
	Email     string                  `json:"email" yaml:"email"`
	Name      string                  `json:"name" yaml:"name"`
	Status    *UserStatus             `json:"status,omitempty" yaml:"status,omitempty"`
	Address   *common.AddressResponse `json:"address,omitempty" yaml:"address,omitempty"`
	CreatedAt *model.UTCTime          `json:"createdAt,omitempty" yaml:"createdAt,omitempty"`
}

func (m *UserRequest) SetDefaults() {
	if m.Status == nil {
		v := UserStatusActive
		m.Status = &v
	}
}

func (m *UserResponse) SetDefaults() {
	if m.Status == nil {
		v := UserStatusActive
		m.Status = &v
	}
}
