// Code generated by oapigen, DO NOT EDIT.

package client

import (
	"context"
	"fmt"
	model "nschugorev/oapigenerator/testdata/project/golden/minimal/model"
)

type ClientSugared struct {
	impl Client
}

func NewClientSugared(impl Client) *ClientSugared {
	return &ClientSugared{impl: impl}
}

func (x *ClientSugared) ListItems(ctx context.Context, req *ListItemsRequest) (*model.Items, error) {
	resp, err := x.impl.ListItems(ctx, req)
	if err != nil {
		return nil, err
	}
	if resp.Response200 != nil {
		return resp.Response200, nil
	}
	return nil, fmt.Errorf("unexpected status: %d", resp.Code)
}

func (x *ClientSugared) CreateItem(ctx context.Context, req *CreateItemRequest) (*model.Item, error) {
	resp, err := x.impl.CreateItem(ctx, req)
	if err != nil {
		return nil, err
	}
	if resp.Response201 != nil {
		return resp.Response201, nil
	}
	return nil, fmt.Errorf("unexpected status: %d", resp.Code)
}

func (x *ClientSugared) GetItem(ctx context.Context, req *GetItemRequest) (*model.Item, error) {
	resp, err := x.impl.GetItem(ctx, req)
	if err != nil {
		return nil, err
	}
	if resp.Response200 != nil {
		return resp.Response200, nil
	}
	return nil, fmt.Errorf("unexpected status: %d", resp.Code)
}

func (x *ClientSugared) UpdateItem(ctx context.Context, req *UpdateItemRequest) (*model.Item, error) {
	resp, err := x.impl.UpdateItem(ctx, req)
	if err != nil {
		return nil, err
	}
	if resp.Response200 != nil {
		return resp.Response200, nil
	}
	return nil, fmt.Errorf("unexpected status: %d", resp.Code)
}

func (x *ClientSugared) DeleteItem(ctx context.Context, req *DeleteItemRequest) error {
	resp, err := x.impl.DeleteItem(ctx, req)
	if err != nil {
		return err
	}
	if resp.Response204 {
		return nil
	}
	return fmt.Errorf("unexpected status: %d", resp.Code)
}
