// Code generated by oapigen, DO NOT EDIT.

package client

import (
	"context"
	model "nschugorev/oapigenerator/testdata/project/golden/minimal/model"
)

type Client interface {
	ListItems(ctx context.Context, req *ListItemsRequest) (*ListItemsResponse, error)
	CreateItem(ctx context.Context, req *CreateItemRequest) (*CreateItemResponse, error)
	GetItem(ctx context.Context, req *GetItemRequest) (*GetItemResponse, error)
	UpdateItem(ctx context.Context, req *UpdateItemRequest) (*UpdateItemResponse, error)
	DeleteItem(ctx context.Context, req *DeleteItemRequest) (*DeleteItemResponse, error)
}

type ListItemsRequest struct {
	Limit *int    `query:"limit"`
	Tag   *string `query:"tag"`
}

type ListItemsResponse struct {
	Code        int
	Response200 *model.Items
	Response400 bool
}

type CreateItemRequest struct {
	Body model.ItemCreate `json:"-"`
}

type CreateItemResponse struct {
	Code        int
	Response201 *model.Item
	Response400 bool
}

type GetItemRequest struct {
	ID string `param:"id"`
}

type GetItemResponse struct {
	Code        int
	Response200 *model.Item
	Response404 bool
}

type UpdateItemRequest struct {
	Body model.ItemCreate `json:"-"`
}

type UpdateItemResponse struct {
	Code        int
	Response200 *model.Item
	Response400 bool
}

type DeleteItemRequest struct {
	ID string `param:"id"`
}

type DeleteItemResponse struct {
	Code        int
	Response204 bool
}
