// Code generated by oapigen (v1.3.6), DO NOT EDIT.

package client

type CreateUserRequestAuditData struct {
	Body any
}

func (req *CreateUserRequest) GetAuditData() any {
	am := CreateUserRequestAuditData{}
	am.Body = req.Body.GetAuditData()
	return am
}

type CreateUserResponse201AuditData struct {
	Payload any
}

func (resp *CreateUserResponse) Response201AuditData() CreateUserResponse201AuditData {
	am := CreateUserResponse201AuditData{}
	if resp.Response201 != nil {
		am.Payload = resp.Response201.GetAuditData()
	}
	return am
}
