// Code generated by oapigen (v1.2.0), DO NOT EDIT.

package client

import (
	"context"
	users "github.com/ilovepitsa/oapicodegen/testdata/onefile/golden/onefile/model/users"
)

type Client interface {
	CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error)
}

type CreateUserRequest struct {
	Body users.UserRequest `json:"-"`
}

type CreateUserResponse struct {
	Code        int
	Response201 *users.UserResponse
	Response400 bool
}
