// Code generated by oapigen (v1.3.3), DO NOT EDIT.

package client

import (
	"context"
	"fmt"
	users "github.com/ilovepitsa/oapicodegen/testdata/onefile/golden/onefile/model/users"
)

type ClientSugared struct {
	impl Client
}

func NewClientSugared(impl Client) *ClientSugared {
	return &ClientSugared{impl: impl}
}

func (x *ClientSugared) CreateUser(ctx context.Context, req *CreateUserRequest) (*users.UserResponse, error) {
	resp, err := x.impl.CreateUser(ctx, req)
	if err != nil {
		return nil, err
	}
	if resp.Response201 != nil {
		return resp.Response201, nil
	}
	return nil, fmt.Errorf("unexpected status: %d", resp.Code)
}
