// Code generated by oapigen (v1.3.1), DO NOT EDIT.

package sdk

import (
	"fmt"
	httpclient "github.com/ilovepitsa/oapicodegen/pkg/httpclient"
	implclient "github.com/ilovepitsa/oapicodegen/testdata/onefile/golden/onefile/impl/httpclient"
	apiclient "github.com/ilovepitsa/oapicodegen/testdata/onefile/golden/onefile/interfaces/client"
)

type SDK struct {
	apiclient.Client
}

func NewSDK(baseURL string, opts ...httpclient.Option) (*SDK, error) {
	c, err := implclient.NewClient(baseURL, opts...)
	if err != nil {
		return nil, fmt.Errorf("init sdk client: %w", err)
	}
	return &SDK{Client: c}, nil
}

func NewSDKFromClient(c apiclient.Client) *SDK {
	return &SDK{Client: c}
}
