// Code generated by oapigen, DO NOT EDIT.

package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	httpclient "nschugorev/oapigenerator/pkg/httpclient"
	apiclient "nschugorev/oapigenerator/testdata/minimal/golden/interfaces/client"
	model "nschugorev/oapigenerator/testdata/minimal/golden/model"
	"strings"
)

var _ apiclient.Client = (*Client)(nil)

type Client struct {
	http *httpclient.Client
}

func NewClient(baseURL string, opts ...httpclient.Option) (*Client, error) {
	c, err := httpclient.NewClient(baseURL, opts...)
	if err != nil {
		return nil, err
	}
	return &Client{http: c}, nil
}

func (c *Client) ListItems(ctx context.Context, req *apiclient.ListItemsRequest) (*apiclient.ListItemsResponse, error) {
	path := "/items"
	q := url.Values{}
	if req.Limit != nil {
		q.Set("limit", fmt.Sprint(*req.Limit))
	}
	if req.Tag != nil {
		q.Set("tag", fmt.Sprint(*req.Tag))
	}
	u := *c.http.ServerURL()
	u.Path = strings.TrimSuffix(u.Path, "/") + path
	u.RawQuery = q.Encode()
	httpReq, err := http.NewRequestWithContext(ctx, "GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	resp, err := c.http.Do(ctx, httpReq)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	result := &apiclient.ListItemsResponse{Code: resp.StatusCode}
	switch resp.StatusCode {
	case 200:
		var v model.Items
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode 200: %w", err)
		}
		result.Response200 = &v
	case 400:
		result.Response400 = true
	default:
		return nil, fmt.Errorf("unexpected status code: %d", resp.StatusCode)
	}
	return result, nil
}

func (c *Client) CreateItem(ctx context.Context, req *apiclient.CreateItemRequest) (*apiclient.CreateItemResponse, error) {
	path := "/items"
	u := *c.http.ServerURL()
	u.Path = strings.TrimSuffix(u.Path, "/") + path
	body, err := json.Marshal(req.Body)
	if err != nil {
		return nil, fmt.Errorf("encode body: %w", err)
	}
	httpReq, err := http.NewRequestWithContext(ctx, "POST", u.String(), bytes.NewReader(body))
	if err != nil {
		return nil, err
	}
	httpReq.Header.Set("Content-Type", "application/json")
	resp, err := c.http.Do(ctx, httpReq)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	result := &apiclient.CreateItemResponse{Code: resp.StatusCode}
	switch resp.StatusCode {
	case 201:
		var v model.Item
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode 201: %w", err)
		}
		result.Response201 = &v
	case 400:
		result.Response400 = true
	default:
		return nil, fmt.Errorf("unexpected status code: %d", resp.StatusCode)
	}
	return result, nil
}

func (c *Client) GetItem(ctx context.Context, req *apiclient.GetItemRequest) (*apiclient.GetItemResponse, error) {
	path := "/items/{id}"
	path = strings.Replace(path, "{id}", url.PathEscape(fmt.Sprint(req.ID)), 1)
	u := *c.http.ServerURL()
	u.Path = strings.TrimSuffix(u.Path, "/") + path
	httpReq, err := http.NewRequestWithContext(ctx, "GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	resp, err := c.http.Do(ctx, httpReq)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	result := &apiclient.GetItemResponse{Code: resp.StatusCode}
	switch resp.StatusCode {
	case 200:
		var v model.Item
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode 200: %w", err)
		}
		result.Response200 = &v
	case 404:
		result.Response404 = true
	default:
		return nil, fmt.Errorf("unexpected status code: %d", resp.StatusCode)
	}
	return result, nil
}

func (c *Client) UpdateItem(ctx context.Context, req *apiclient.UpdateItemRequest) (*apiclient.UpdateItemResponse, error) {
	path := "/items/{id}"
	u := *c.http.ServerURL()
	u.Path = strings.TrimSuffix(u.Path, "/") + path
	body, err := json.Marshal(req.Body)
	if err != nil {
		return nil, fmt.Errorf("encode body: %w", err)
	}
	httpReq, err := http.NewRequestWithContext(ctx, "PUT", u.String(), bytes.NewReader(body))
	if err != nil {
		return nil, err
	}
	httpReq.Header.Set("Content-Type", "application/json")
	resp, err := c.http.Do(ctx, httpReq)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	result := &apiclient.UpdateItemResponse{Code: resp.StatusCode}
	switch resp.StatusCode {
	case 200:
		var v model.Item
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode 200: %w", err)
		}
		result.Response200 = &v
	case 400:
		result.Response400 = true
	default:
		return nil, fmt.Errorf("unexpected status code: %d", resp.StatusCode)
	}
	return result, nil
}

func (c *Client) DeleteItem(ctx context.Context, req *apiclient.DeleteItemRequest) (*apiclient.DeleteItemResponse, error) {
	path := "/items/{id}"
	path = strings.Replace(path, "{id}", url.PathEscape(fmt.Sprint(req.ID)), 1)
	u := *c.http.ServerURL()
	u.Path = strings.TrimSuffix(u.Path, "/") + path
	httpReq, err := http.NewRequestWithContext(ctx, "DELETE", u.String(), nil)
	if err != nil {
		return nil, err
	}
	resp, err := c.http.Do(ctx, httpReq)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	result := &apiclient.DeleteItemResponse{Code: resp.StatusCode}
	switch resp.StatusCode {
	case 204:
		result.Response204 = true
	default:
		return nil, fmt.Errorf("unexpected status code: %d", resp.StatusCode)
	}
	return result, nil
}
