// Code generated by oapigen (v2.0.0), DO NOT EDIT.

package sdk

import (
	"fmt"
	implclient "github.com/ilovepitsa/oapicodegen/internal/generator/testdata/golden/petstore/impl/httpclient"
	apiclient "github.com/ilovepitsa/oapicodegen/internal/generator/testdata/golden/petstore/interfaces/client"
	httpclient "github.com/ilovepitsa/oapicodegen/pkg/httpclient"
)

type SDK struct {
	apiclient.Client
}

func NewSDK(baseURL string, opts ...httpclient.Option) (*SDK, error) {
	c, err := implclient.NewClient(baseURL, opts...)
	if err != nil {
		return nil, fmt.Errorf("init sdk client: %w", err)
	}
	return &SDK{Client: c}, nil
}

func NewSDKFromClient(c apiclient.Client) *SDK {
	return &SDK{Client: c}
}
