// Code generated by oapigen, DO NOT EDIT.

package sdk

import (
	"fmt"
	implclient "nschugorev/oapigenerator/internal/generator/testdata/golden/petstore/impl/vanillahttp/client"
	apiclient "nschugorev/oapigenerator/internal/generator/testdata/golden/petstore/interfaces/client"
	httpclient "nschugorev/oapigenerator/pkg/httpclient"
)

type SDK struct {
	apiclient.Client
}

func NewSDK(baseURL string, opts ...httpclient.Option) (*SDK, error) {
	c, err := implclient.NewClient(baseURL, opts...)
	if err != nil {
		return nil, fmt.Errorf("init sdk client: %w", err)
	}
	return &SDK{Client: c}, nil
}

func NewSDKFromClient(c apiclient.Client) *SDK {
	return &SDK{Client: c}
}
