// Code generated by oapigen (v1.2.0), DO NOT EDIT.

package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	httpclient "github.com/ilovepitsa/oapicodegen/pkg/httpclient"
	apiclient "github.com/ilovepitsa/oapicodegen/testdata/onefile/golden/onefile/interfaces/client"
	users "github.com/ilovepitsa/oapicodegen/testdata/onefile/golden/onefile/model/users"
	"net/http"
	"strings"
)

var _ apiclient.Client = (*Client)(nil)

type Client struct {
	http *httpclient.Client
}

func NewClient(baseURL string, opts ...httpclient.Option) (*Client, error) {
	c, err := httpclient.NewClient(baseURL, opts...)
	if err != nil {
		return nil, err
	}
	return &Client{http: c}, nil
}

func (c *Client) CreateUser(ctx context.Context, req *apiclient.CreateUserRequest) (*apiclient.CreateUserResponse, error) {
	path := "/users"
	u := *c.http.ServerURL()
	u.Path = strings.TrimSuffix(u.Path, "/") + path
	body, err := json.Marshal(req.Body)
	if err != nil {
		return nil, fmt.Errorf("encode body: %w", err)
	}
	httpReq, err := http.NewRequestWithContext(ctx, "POST", u.String(), bytes.NewReader(body))
	if err != nil {
		return nil, err
	}
	httpReq.Header.Set("Content-Type", "application/json")
	resp, err := c.http.Do(ctx, httpReq)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	result := &apiclient.CreateUserResponse{Code: resp.StatusCode}
	switch resp.StatusCode {
	case 201:
		var v users.UserResponse
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode 201: %w", err)
		}
		result.Response201 = &v
	case 400:
		result.Response400 = true
	default:
		return nil, fmt.Errorf("unexpected status code: %d", resp.StatusCode)
	}
	return result, nil
}
