package main

import (
	"bytes"
	"os"
	"strings"
	"testing"

	"github.com/ilovepitsa/oapicodegen/internal/version"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestMain фиксирует версию генератора в v1.3.0 перед запуском тестов пакета.
// e2e-тест генерирует файлы, заголовки которых сравниваются с golden-файлами,
// хранящими «Code generated by oapigen (v1.3.0), DO NOT EDIT.».
func TestMain(m *testing.M) {
	version.Set("v1.3.0")
	os.Exit(m.Run())
}

// TestRun_VersionFlag проверяет, что --version печатает «oapigen (v1.3.0)»
// в stdout и завершается без ошибки. Вывод направляется в stdout (не stderr),
// как принято для --version у CLI-инструментов.
func TestRun_VersionFlag(t *testing.T) {
	// Не t.Parallel(): тест мутирует процесс-глобальный os.Stdout, что
	// гоняется с параллельными тестами. Восстановление через defer —
	// корректно даже при панике внутри run.
	orig := os.Stdout
	r, w, err := os.Pipe()
	require.NoError(t, err)
	defer func() { os.Stdout = orig }()

	os.Stdout = w

	err = run([]string{"--version"}, nullFile(t))

	_ = w.Close()
	require.NoError(t, err)

	var buf bytes.Buffer
	_, _ = buf.ReadFrom(r)
	got := buf.String()
	assert.True(t, strings.Contains(got, "oapigen (v1.3.0)"),
		"expected --version output to contain 'oapigen (v1.3.0)'; got %q", got)
}
