// Code generated by oapigen (v1.2.0), DO NOT EDIT.

package server

import (
	"context"
	client "github.com/ilovepitsa/oapicodegen/internal/generator/testdata/golden/petstore/interfaces/client"
)

type Server interface {
	ListPets(ctx context.Context, req *client.ListPetsRequest) (*client.ListPetsResponse, error)
	CreatePet(ctx context.Context, req *client.CreatePetRequest) (*client.CreatePetResponse, error)
	GetPet(ctx context.Context, req *client.GetPetRequest) (*client.GetPetResponse, error)
}
