// Code generated by oapigen, DO NOT EDIT.

package client

type ListPetsRequestAuditData struct {
	Limit *int
}

func (req *ListPetsRequest) GetAuditData() any {
	am := ListPetsRequestAuditData{
		Limit: req.Limit,
	}
	return am
}

type CreatePetRequestAuditData struct {
	Body any
}

func (req *CreatePetRequest) GetAuditData() any {
	am := CreatePetRequestAuditData{}
	am.Body = req.Body.GetAuditData()
	return am
}

type GetPetRequestAuditData struct {
	ID string
}

func (req *GetPetRequest) GetAuditData() any {
	am := GetPetRequestAuditData{
		ID: req.ID,
	}
	return am
}

type ListPetsResponse200AuditData struct {
	Payload any
}

func (resp *ListPetsResponse) Response200AuditData() ListPetsResponse200AuditData {
	am := ListPetsResponse200AuditData{}
	if resp.Response200 != nil {
		am.Payload = resp.Response200.GetAuditData()
	}
	return am
}

type CreatePetResponse201AuditData struct {
	Payload any
}

func (resp *CreatePetResponse) Response201AuditData() CreatePetResponse201AuditData {
	am := CreatePetResponse201AuditData{}
	if resp.Response201 != nil {
		am.Payload = resp.Response201.GetAuditData()
	}
	return am
}

type GetPetResponse200AuditData struct {
	Payload any
}

func (resp *GetPetResponse) Response200AuditData() GetPetResponse200AuditData {
	am := GetPetResponse200AuditData{}
	if resp.Response200 != nil {
		am.Payload = resp.Response200.GetAuditData()
	}
	return am
}

type GetPetResponse404AuditData struct {
	Payload any
}

func (resp *GetPetResponse) Response404AuditData() GetPetResponse404AuditData {
	am := GetPetResponse404AuditData{}
	if resp.Response404 != nil {
		am.Payload = resp.Response404.GetAuditData()
	}
	return am
}
