// Code generated by oapigen (v1.2.0), DO NOT EDIT.

package client

import (
	"context"
	model "github.com/ilovepitsa/oapicodegen/internal/generator/testdata/golden/petstore/model"
)

type Client interface {
	ListPets(ctx context.Context, req *ListPetsRequest) (*ListPetsResponse, error)
	CreatePet(ctx context.Context, req *CreatePetRequest) (*CreatePetResponse, error)
	GetPet(ctx context.Context, req *GetPetRequest) (*GetPetResponse, error)
}

type ListPetsRequest struct {
	Limit *int `query:"limit"`
}

type ListPetsResponse struct {
	Code            int
	Response200     *model.Pets
	ResponseDefault *model.Error
}

type CreatePetRequest struct {
	Body model.NewPet `json:"-"`
}

type CreatePetResponse struct {
	Code        int
	Response201 *model.Pet
}

type GetPetRequest struct {
	ID string `param:"id"`
}

type GetPetResponse struct {
	Code        int
	Response200 *model.Pet
	Response404 *model.Error
}
