// Code generated by oapigen, DO NOT EDIT.

package client

import (
	"context"
	"fmt"
	model "nschugorev/oapigenerator/internal/generator/testdata/golden/petstore/model"
)

type ClientSugared struct {
	impl Client
}

func NewClientSugared(impl Client) *ClientSugared {
	return &ClientSugared{impl: impl}
}

func (x *ClientSugared) ListPets(ctx context.Context, req *ListPetsRequest) (*model.Pets, error) {
	resp, err := x.impl.ListPets(ctx, req)
	if err != nil {
		return nil, err
	}
	if resp.Response200 != nil {
		return resp.Response200, nil
	}
	return nil, fmt.Errorf("unexpected status: %d", resp.Code)
}

func (x *ClientSugared) CreatePet(ctx context.Context, req *CreatePetRequest) (*model.Pet, error) {
	resp, err := x.impl.CreatePet(ctx, req)
	if err != nil {
		return nil, err
	}
	if resp.Response201 != nil {
		return resp.Response201, nil
	}
	return nil, fmt.Errorf("unexpected status: %d", resp.Code)
}

func (x *ClientSugared) GetPet(ctx context.Context, req *GetPetRequest) (*model.Pet, error) {
	resp, err := x.impl.GetPet(ctx, req)
	if err != nil {
		return nil, err
	}
	if resp.Response200 != nil {
		return resp.Response200, nil
	}
	return nil, fmt.Errorf("unexpected status: %d", resp.Code)
}
