// Code generated by oapigen (v1.3.5), DO NOT EDIT.

package mock_client

import (
	"context"
	apiclient "github.com/ilovepitsa/oapicodegen/testdata/onefile/golden/onefile/interfaces/client"
	"go.uber.org/mock/gomock"
	"reflect"
)

var _ apiclient.Client = (*MockClient)(nil)

type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

type MockClientMockRecorder struct {
	mock *MockClient
}

func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

func (m *MockClient) CreateUser(arg0 context.Context, arg1 *apiclient.CreateUserRequest) (*apiclient.CreateUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(*apiclient.CreateUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockClientMockRecorder) CreateUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockClient)(nil).CreateUser), arg0, arg1)
}
