// Code generated by oapigen, DO NOT EDIT.

package mock_server

import (
	"context"
	"go.uber.org/mock/gomock"
	apiclient "nschugorev/oapigenerator/internal/generator/testdata/golden/petstore/interfaces/client"
	apiserver "nschugorev/oapigenerator/internal/generator/testdata/golden/petstore/interfaces/server"
	"reflect"
)

var _ apiserver.Server = (*MockServer)(nil)

type MockServer struct {
	ctrl     *gomock.Controller
	recorder *MockServerMockRecorder
}

type MockServerMockRecorder struct {
	mock *MockServer
}

func NewMockServer(ctrl *gomock.Controller) *MockServer {
	mock := &MockServer{ctrl: ctrl}
	mock.recorder = &MockServerMockRecorder{mock}
	return mock
}

func (m *MockServer) EXPECT() *MockServerMockRecorder {
	return m.recorder
}

func (m *MockServer) ListPets(arg0 context.Context, arg1 *apiclient.ListPetsRequest) (*apiclient.ListPetsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPets", arg0, arg1)
	ret0, _ := ret[0].(*apiclient.ListPetsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServerMockRecorder) ListPets(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPets", reflect.TypeOf((*MockServer)(nil).ListPets), arg0, arg1)
}

func (m *MockServer) CreatePet(arg0 context.Context, arg1 *apiclient.CreatePetRequest) (*apiclient.CreatePetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePet", arg0, arg1)
	ret0, _ := ret[0].(*apiclient.CreatePetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServerMockRecorder) CreatePet(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePet", reflect.TypeOf((*MockServer)(nil).CreatePet), arg0, arg1)
}

func (m *MockServer) GetPet(arg0 context.Context, arg1 *apiclient.GetPetRequest) (*apiclient.GetPetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPet", arg0, arg1)
	ret0, _ := ret[0].(*apiclient.GetPetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServerMockRecorder) GetPet(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPet", reflect.TypeOf((*MockServer)(nil).GetPet), arg0, arg1)
}
