// Code generated by oapigen (v1.3.1), DO NOT EDIT.

package mock_server

import (
	"context"
	apiclient "github.com/ilovepitsa/oapicodegen/testdata/onefile/golden/onefile/interfaces/client"
	apiserver "github.com/ilovepitsa/oapicodegen/testdata/onefile/golden/onefile/interfaces/server"
	"go.uber.org/mock/gomock"
	"reflect"
)

var _ apiserver.Server = (*MockServer)(nil)

type MockServer struct {
	ctrl     *gomock.Controller
	recorder *MockServerMockRecorder
}

type MockServerMockRecorder struct {
	mock *MockServer
}

func NewMockServer(ctrl *gomock.Controller) *MockServer {
	mock := &MockServer{ctrl: ctrl}
	mock.recorder = &MockServerMockRecorder{mock}
	return mock
}

func (m *MockServer) EXPECT() *MockServerMockRecorder {
	return m.recorder
}

func (m *MockServer) CreateUser(arg0 context.Context, arg1 *apiclient.CreateUserRequest) (*apiclient.CreateUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(*apiclient.CreateUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServerMockRecorder) CreateUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockServer)(nil).CreateUser), arg0, arg1)
}
