// Code generated by oapigen (v1.3.1), DO NOT EDIT.

package server

import (
	"context"
	client "github.com/ilovepitsa/oapicodegen/testdata/onefile/golden/onefile/interfaces/client"
)

type Server interface {
	CreateUser(ctx context.Context, req *client.CreateUserRequest) (*client.CreateUserResponse, error)
}
