// Code generated by oapigen, DO NOT EDIT.

package mock_server

import (
	"context"
	"go.uber.org/mock/gomock"
	apiclient "nschugorev/oapigenerator/testdata/project/golden/minimal/interfaces/client"
	apiserver "nschugorev/oapigenerator/testdata/project/golden/minimal/interfaces/server"
	"reflect"
)

var _ apiserver.Server = (*MockServer)(nil)

type MockServer struct {
	ctrl     *gomock.Controller
	recorder *MockServerMockRecorder
}

type MockServerMockRecorder struct {
	mock *MockServer
}

func NewMockServer(ctrl *gomock.Controller) *MockServer {
	mock := &MockServer{ctrl: ctrl}
	mock.recorder = &MockServerMockRecorder{mock}
	return mock
}

func (m *MockServer) EXPECT() *MockServerMockRecorder {
	return m.recorder
}

func (m *MockServer) ListItems(arg0 context.Context, arg1 *apiclient.ListItemsRequest) (*apiclient.ListItemsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListItems", arg0, arg1)
	ret0, _ := ret[0].(*apiclient.ListItemsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServerMockRecorder) ListItems(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListItems", reflect.TypeOf((*MockServer)(nil).ListItems), arg0, arg1)
}

func (m *MockServer) CreateItem(arg0 context.Context, arg1 *apiclient.CreateItemRequest) (*apiclient.CreateItemResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateItem", arg0, arg1)
	ret0, _ := ret[0].(*apiclient.CreateItemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServerMockRecorder) CreateItem(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateItem", reflect.TypeOf((*MockServer)(nil).CreateItem), arg0, arg1)
}

func (m *MockServer) GetItem(arg0 context.Context, arg1 *apiclient.GetItemRequest) (*apiclient.GetItemResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItem", arg0, arg1)
	ret0, _ := ret[0].(*apiclient.GetItemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServerMockRecorder) GetItem(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItem", reflect.TypeOf((*MockServer)(nil).GetItem), arg0, arg1)
}

func (m *MockServer) UpdateItem(arg0 context.Context, arg1 *apiclient.UpdateItemRequest) (*apiclient.UpdateItemResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItem", arg0, arg1)
	ret0, _ := ret[0].(*apiclient.UpdateItemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServerMockRecorder) UpdateItem(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItem", reflect.TypeOf((*MockServer)(nil).UpdateItem), arg0, arg1)
}

func (m *MockServer) DeleteItem(arg0 context.Context, arg1 *apiclient.DeleteItemRequest) (*apiclient.DeleteItemResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", arg0, arg1)
	ret0, _ := ret[0].(*apiclient.DeleteItemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServerMockRecorder) DeleteItem(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockServer)(nil).DeleteItem), arg0, arg1)
}
