// Code generated by oapigen, DO NOT EDIT.

package petstore

import (
	"context"
)

type Client interface {
	ListPets(ctx context.Context, req *ListPetsRequest) (*ListPetsResponse, error)
	CreatePet(ctx context.Context, req *CreatePetRequest) (*CreatePetResponse, error)
	GetPet(ctx context.Context, req *GetPetRequest) (*GetPetResponse, error)
}

type ListPetsRequest struct {
	Limit *int // query: "limit"
}

type ListPetsResponse struct {
	Code            int
	Response200     *Pets
	ResponseDefault *Error
}

type CreatePetRequest struct {
	Body NewPet // body
}

type CreatePetResponse struct {
	Code        int
	Response201 *Pet
}

type GetPetRequest struct {
	ID string // path: "id"
}

type GetPetResponse struct {
	Code        int
	Response200 *Pet
	Response404 *Error
}
