// Code generated by oapigen, DO NOT EDIT.

package petstore

import (
	"encoding/json"
	"fmt"
)

func (m *PetKind) UnmarshalJSON(data []byte) error {
	var v_0 Pet
	if err := json.Unmarshal(data, &v_0); err == nil {
		m.Pet = &v_0
		return nil
	}
	var v_1 NewPet
	if err := json.Unmarshal(data, &v_1); err == nil {
		m.NewPet = &v_1
		return nil
	}
	return fmt.Errorf("PetKind: no variant matched")
}

func (m PetKind) MarshalJSON() ([]byte, error) {
	if m.Pet != nil {
		return json.Marshal(m.Pet)
	}
	if m.NewPet != nil {
		return json.Marshal(m.NewPet)
	}
	return json.Marshal(nil)
}
