// Code generated by oapigen, DO NOT EDIT.

package petstore

import (
	"context"
)

type Server interface {
	ListPets(ctx context.Context, req *ListPetsRequest) (*ListPetsResponse, error)
	CreatePet(ctx context.Context, req *CreatePetRequest) (*CreatePetResponse, error)
	GetPet(ctx context.Context, req *GetPetRequest) (*GetPetResponse, error)
}
