// Code generated by oapigen, DO NOT EDIT.

package model

type Item struct {
	ID       string            `json:"id" yaml:"id"`
	Name     string            `json:"name" yaml:"name"`
	Kind     Kind              `json:"kind" yaml:"kind"`
	Tag      *string           `json:"tag,omitempty" yaml:"tag,omitempty"`
	Metadata map[string]string `json:"metadata,omitempty" yaml:"metadata,omitempty"`
}
