// Code generated by oapigen, DO NOT EDIT.

package model

type ItemCreate struct {
	Name string  `json:"name" yaml:"name"`
	Kind Kind    `json:"kind" yaml:"kind"`
	Tag  *string `json:"tag,omitempty" yaml:"tag,omitempty"`
}
