// Code generated by oapigen, DO NOT EDIT.

package model

import (
	sensitive "nschugorev/oapigenerator/pkg/sensitive"
)

type ItemAuditData struct {
	ID       string                       `json:"id" yaml:"id"`
	Name     string                       `json:"name" yaml:"name"`
	Kind     Kind                         `json:"kind" yaml:"kind"`
	Tag      *string                      `json:"tag,omitempty" yaml:"tag,omitempty"`
	Secret   *sensitive.Sensitive[string] `json:"secret,omitempty" yaml:"secret,omitempty"`
	Metadata map[string]string            `json:"metadata,omitempty" yaml:"metadata,omitempty"`
}

func (m Item) GetAuditData() any {
	var am ItemAuditData
	am.ID = m.ID
	am.Name = m.Name
	am.Kind = m.Kind
	am.Tag = m.Tag
	if m.Secret != nil {
		v := sensitive.New(*m.Secret)
		am.Secret = &v
	}
	am.Metadata = m.Metadata
	return am
}
