package generator

import (
	"os"
	"testing"

	"github.com/ilovepitsa/oapicodegen/internal/version"
)

// TestMain фиксирует версию генератора в v1.2.0 перед запуском тестов пакета.
// Это обеспечивает детерминированное совпадение заголовков сгенерированных
// файлов («Code generated by oapigen (v1.2.0), DO NOT EDIT.») с golden-файлами
// без зависимости от ldflags сборки (go test ./... без -ldflags).
func TestMain(m *testing.M) {
	version.Set("v1.2.0")
	os.Exit(m.Run())
}
