// Code generated by oapigen (v1.3.6), DO NOT EDIT.

package model

type AddressRequest struct {
	Street string  `json:"street" yaml:"street"`
	City   string  `json:"city" yaml:"city"`
	Zip    *string `json:"zip,omitempty" yaml:"zip,omitempty"`
}

type AddressResponse struct {
	Street string  `json:"street" yaml:"street"`
	City   string  `json:"city" yaml:"city"`
	Zip    *string `json:"zip,omitempty" yaml:"zip,omitempty"`
}
