// Code generated by oapigen (v1.3.4), DO NOT EDIT.

package model

func AddressRequestToResponse(req AddressRequest) AddressResponse {
	var resp AddressResponse
	resp.Street = req.Street
	resp.City = req.City
	resp.Zip = req.Zip
	return resp
}
