// Code generated by oapigen (v2.0.0), DO NOT EDIT.

package model

import (
	"fmt"
	validator "github.com/ilovepitsa/oapicodegen/pkg/validator"
)

type DeletedEvent struct {
	Type   string `json:"type" yaml:"type"`
	ItemID string `json:"itemId" yaml:"itemId"`
}

func (x DeletedEvent) ValidateOwn(reg *validator.Registry) error {
	if len(x.ItemID) < 1 {
		return fmt.Errorf("field ItemID: must be >= 1")
	}
	return nil
}
