// Code generated by oapigen, DO NOT EDIT.

package model

import (
	"encoding/json"
	"fmt"
)

func (m *Event) UnmarshalJSON(data []byte) error {
	var v_0 CreatedEvent
	if err := json.Unmarshal(data, &v_0); err == nil {
		m.CreatedEvent = &v_0
		return nil
	}
	var v_1 DeletedEvent
	if err := json.Unmarshal(data, &v_1); err == nil {
		m.DeletedEvent = &v_1
		return nil
	}
	return fmt.Errorf("Event: no variant matched")
}

func (m Event) MarshalJSON() ([]byte, error) {
	if m.CreatedEvent != nil {
		return json.Marshal(m.CreatedEvent)
	}
	if m.DeletedEvent != nil {
		return json.Marshal(m.DeletedEvent)
	}
	return json.Marshal(nil)
}
