// Code generated by oapigen (v1.3.3), DO NOT EDIT.

package model

// ExpectedValidatorNames возвращает отсортированный уникальный список
// имён named-валидаторов, на которые ссылаются x-validations схем.
// Используется с validator.Registry.AssertExact при старте приложения
// для проверки, что все валидаторы зарегистрированы.
func ExpectedValidatorNames() []string {
	return []string{
		"app.ItemConsistency",
		"app.ItemCreateConsistency",
		"app.NonEmptyName",
	}
}
