// Code generated by oapigen, DO NOT EDIT.

package model

import (
	sensitive "nschugorev/oapigenerator/pkg/sensitive"
)

type ItemCreateAuditData struct {
	Name   string                       `json:"name" yaml:"name"`
	Kind   Kind                         `json:"kind" yaml:"kind"`
	Tag    *string                      `json:"tag,omitempty" yaml:"tag,omitempty"`
	Secret *sensitive.Sensitive[string] `json:"secret,omitempty" yaml:"secret,omitempty"`
}

func (m ItemCreate) GetAuditData() any {
	var am ItemCreateAuditData
	am.Name = m.Name
	am.Kind = m.Kind
	am.Tag = m.Tag
	if m.Secret != nil {
		v := sensitive.New(*m.Secret)
		am.Secret = &v
	}
	return am
}
