// Code generated by oapigen, DO NOT EDIT.

package model

type NewPetAuditData struct {
	Name string  `json:"name" yaml:"name"`
	Tag  *string `json:"tag,omitempty" yaml:"tag,omitempty"`
}

func (m NewPet) GetAuditData() any {
	var am NewPetAuditData
	am.Name = m.Name
	am.Tag = m.Tag
	return am
}
