// Code generated by oapigen, DO NOT EDIT.

package model

type Pet struct {
	ID     int64   `json:"id" yaml:"id"`
	Name   string  `json:"name" yaml:"name"`
	Tag    *string `json:"tag,omitempty" yaml:"tag,omitempty"`
	Status *string `json:"status,omitempty" yaml:"status,omitempty"`
}
