// Code generated by oapigen, DO NOT EDIT.

package model

type PetAuditData struct {
	ID     int64   `json:"id" yaml:"id"`
	Name   string  `json:"name" yaml:"name"`
	Tag    *string `json:"tag,omitempty" yaml:"tag,omitempty"`
	Status *string `json:"status,omitempty" yaml:"status,omitempty"`
}

func (m Pet) GetAuditData() any {
	var am PetAuditData
	am.ID = m.ID
	am.Name = m.Name
	am.Tag = m.Tag
	am.Status = m.Status
	return am
}
